DROP TABLE JOUEUR IF EXISTS;
DROP TABLE EQUIPE IF EXISTS;

CREATE TABLE EQUIPE (
  ID_EQUIPE            BIGINT IDENTITY       NOT NULL,
  NOM_EQUIPE           VARCHAR(255)          NOT NULL,
  LOCALITE_EQUIPE      VARCHAR(255)          NOT NULL,
  DATECREATION_EQUIPE  DATE                  NOT NULL,
  PRIMARY KEY (ID_EQUIPE)
 );
 
CREATE TABLE JOUEUR (
  ID_JOUEUR       BIGINT IDENTITY       NOT NULL,
  NOM_JOUEUR      VARCHAR(255)		    NOT NULL,
  PRENOM_JOUEUR   VARCHAR(255) 		    NOT NULL,
  AGE_JOUEUR      DATE         		    NOT NULL,
  EMAIL_JOUEUR    VARCHAR(255)		    NOT NULL,
  ID_EQUIPE       BIGINT      		    NOT NULL,
  PRIMARY KEY (ID_JOUEUR)
  );
  
ALTER TABLE JOUEUR 
	ADD CONSTRAINT FK355D0780BC290DFE 
	FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE;

 
